name: first workflow
on:
  push:
    branches:
       - main
jobs:
  firstworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: run echo
        run: echo"first workflow run"
  
    
