name: push-pr

on:
    push:
        branches:
            - main
            - "release/**"
    pull_request:
        branches:
            - main
        paths:
            - "src/**"
jobs:
    pushandpr:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.2.2

            - name: list all files
              run: ls -la
            
            - name: test
              run: npm test